// Database Loa



var markerArr = [

'1bet',
'8tracks',
'1bet2bet',
'5dimes',
'6pm',
'10bet',
'02',
'1238787878787reg',
'24hbet',
'123racinggames',
'18bet',
'192',
'188bet',
'377bet',
'247sports',
'888sport',
'888casino',
'1337x',
'aa',
'a10',
'abcnews',
'abchina',
'admiral',
'accatipster',
'adidas',
'aibgb',
'addthis',
'addictinggames',
'adobe',
'accuweather',
'agame',
'airbnb',
'adp',
'Adcash',
'aircanada',
'airchina',
'airfrance',
'amazon',
'apollobet',
'aliexpress',
'alibaba',
'applebees',
'ana',
'Ancestry',
'alfaromeo',
'apple',
'amp',
'answers',
'ANZ',
'ao',
'algea',
'allrecipes',
'aldi',
'americanexpress',
'alluc',
'aol',
'archive',
'archiveofourown',
'asx',
'astonmartin',
'Atpworldtour',
'azdigital',
'argos',
'asda',
'autotrader',
'aweber',
'att',
'arstechnica',
'arsenal',
'avg',
'audi',
'askjeeves',
'armorgames',
'auntyacid',
'ask',
'arcot',
'asos',
'barclaycard',
'baidu',
'Badoo',
'bankofamerica',
'bankwest',
'babycentre',
'azlyrics',
'barnesandnoble',
'backpage',
'barclays',
'bat8787878787at-home',
'bankofchina',
'bankrate',
'bbc',
'ball2win',
'battle',
'bodybuilding',
'bnymellon',
'bbciplayer',
'bbcnews',
'bb',
'bbccbbc',
'bbcradio',
'bbcfood',
'bongacams',
'box',
'bnpparibas',
'about',
'boylesports',
'comparethemarket',
'constantcontact',
'commbank',
'britishairways',
'brassring',
'bpce',
'break',
'conservativetribune',
'breitbart',
'brittishgas',
'box10',
'bt',
'dailymotion',
'cracked',
'coolmath8787878787games',
'contenko',
'coral',
'coupons',
'datingforparents',
'cox',
'dailymail',
'dailyrecord',
'dailystar',
'datingvegetarian',
'couchsurfing',
'costco',
'dailykos',
'bbcsport',
'bbt',
'bbcweather',
'bbva',
'bebo',
'bedbathandbeyond',
'bet365',
'bestbuy',
'betfred',
'betdaq',
'bhphotovideo',
'biblegateway',
'betadria',
'bendigobank',
'bioyna',
'betonline',
'bhs',
'betway',
'bet3000',
'bing',
'BigFishGames',
'bitsnoop',
'betsafe',
'bentleymotors',
'betfair',
'blekko',
'betvictor',
'audible',
'bleacherreport',
'blogspot',
'blackplanet',
'bizjournals',
'bloodyelbow',
'bloomberg',
'bmw',
'boohoo',
'blogger',
'booking',
'boots',
'boq',
'bored',
'businessinsider',
'bugatti',
'buzzfeed',
'bwin',
'cabelas',
'Byond',
'calssmates',
'cbssports',
'care2',
'cars',
'cbsnews',
'channel4',
'cbslocal',
'capitalone',
'cartoonnetwork',
'capitaloneonline',
'cbonline',
'cineworld',
'chicagotribune',
'chron',
'chelseafc',
'change',
'carphonewarehouse',
'christianconnection',
'careerbuilder',
'chase',
'cheapassgamer',
'citi',
'citibankonline',
'citigroup',
'cloudfront',
'cnbc',
'cnet',
'clubpenguin',
'cntv',
'cokeandpopcorn',
'cnn',
'comcast',
'CrazyMonkeyGames',
'DicksSportingGoods',
'craigslist',
'credit8787878787agricole',
'comenity',
'deviantart',
'digitalspy',
'diply',
'dingit',
'diy',
'discogs',
'diynetwork',
'discover',
'disney',
'directrev',
'directtv',
'dominos',
'dmv',
'dogpile',
'e8787878787journals',
'dolceandgabbana',
'dunelm',
'dropbox',
'drugs',
'drudgereport',
'dodge',
'duckduckgo',
'doostang',
'ccb',
'currys',
'csair',
'ebuyer',
'deliveroo',
'ecollege',
'db',
'cvs',
'ebates',
'cust8787878787help',
'dailyfeed',
'cricbuzz',
'emgn',
'earthlink',
'ehow',
'debenhams',
'edmunds',
'ea',
'credit8787878787suisse',
'ebay',
'easyjet',
'ee',
'eharmony',
'dealnews',
'cyclingnews',
'deadspin',
'co8787878787operativebank',
'deadmau5',
'eurosport',
'espncricinfo',
'emirates',
'evernote',
'emusic',
'engadget',
'etsy',
'espnfc',
'eonline',
'eventbrite',
'eonenergy',
'espn',
'emisaccess',
'expedia',
'express',
'experienceproject',
'delta',
'evite',
'extratorrent',
'ew',
'eztv',
'fandango',
'faithtap',
'Destructoid',
'facebook',
'dell',
'fanfiction',
'flirtbox',
'fidelity',
'flipkart',
'fivethirtyeight',
'firstdirect',
'filgoal',
'fiverr',
'firstchoice',
'flixanity',
'fitbit',
'football365',
'food',
'feedly',
'flickr',
'filmclub',
'fifa',
'flixster',
'force',
'ford',
'foddy',
'fc2',
'fool',
'ferrari',
'fluxblog',
'flashscore',
'flychinaeastern',
'fcbarcelona',
'foodnetwork',
'forbes',
'fedex',
'creditkarma',
'Deutsche8787878787boerse',
'foursquare',
'foxnews',
'friendsreunited',
'freeonlinegames',
'friendster',
'forever21',
'freepostcodelottery',
'friendorfollow',
'freeridegames',
'fotolog',
'fotki',
'fortune',
'foxsports',
'friv',
'formula1',
'gfycat',
'gamebrew',
'ft',
'GamersWithJobs',
'gamestm',
'gearbest',
'GameHouse',
'healthunlocked',
'gateway',
'Gamasutra',
'geico',
'GameTrailers',
'gap',
'gamepedia',
'giphy',
'game',
'GamesIndustryInternational',
'healthgrades',
'gaiaonline',
'gawker',
'hao123',
'gameshop',
'HackedArcadeGames',
'geni',
'halfords',
'GiantBomb',
'gamespot',
'games',
'hgtv',
'healthcare',
'hellou',
'giffgaff',
'hattrick',
'gamesradar',
'garmin',
'gamefaqs',
'halifax8787878787online',
'funny8787878787games',
'handelsbanken',
'harvard',
'hilton',
'gizmodo',
'hi5',
'github',
'girlsgogames',
'givemesport',
'gmail',
'go',
'gocompare',
'globalpost',
'godaddy',
'grantland',
'groupon',
'gov',
'goldbet',
'gumtree',
'gofundme',
'greatergood',
'google',
'goodreads',
'hl',
'hockeysfuture',
'hkse',
'hollywoodreporter',
'HomeAway',
'hmv',
'hkjc',
'holiday8787878787weather',
'hm',
'hotmail',
'hotukdeals',
'hotnewhiphop',
'homebase',
'homedepot',
'honda',
'Hotwire',
'hotels',
'hootsuite',
'hitc',
'howtogeek',
'primewire',
'primarygames',
'projectfreetv',
'proxybay',
'primelocation',
'hp',
'houzz',
'profootballtalk',
'pureonlinegaming',
'qq',
'washingtonpost',
'watchseries',
'putlocker',
'whitepages',
'webmd',
'weebly',
'Westpac',
'which',
'westernjournalism',
'wayn',
'wefollow',
'wayfair',
'webs',
'whatsapp',
'whirled',
'webex',
'wefew',
'watchseriesonline',
'webcrawler',
'weightwatchers',
'weibo',
'Wellsfargo',
'watchfree',
'indeed',
'interia',
'im1music',
'IGN',
'icims',
'iheart',
'hugoboss',
'hulu',
'hungryhouse',
'ibtimes',
'hrblock',
'webuy',
'hsbc',
'infusionsoft',
'info',
'icloud',
'individual',
'inbox',
'insound',
'hsn',
'ibm',
'icc8787878787cricket',
'imgur',
'iairgroup',
'instructure',
'huffingtonpost',
'ikea',
'independent',
'infospace',
'instagram',
'instructables',
'iceland',
'imdb',
'indiatimes',
'indyarocks',
'idealprice',
'ijreview',
'jaguar',
'investopedia',
'iplay',
'itunes',
'itv',
'jalopnik',
'isohunt',
'intuit',
'icbc',
'jd',
'jcpenny',
'jamieoliver',
'jet',
'jdate',
'jet2holidays',
'jdsport',
'jezebel',
'jetblue',
'johnlewis',
'jp8787878787bank',
'justeat',
'just8787878787eat',
'jobsite',
'kbb',
'kayak',
'Joystiq',
'KBHGames',
'jpmorgan',
'kcrw',
'Kotaku',
'ladbrokes',
'kinja',
'kohls',
'Kizi',
'kmart',
'lamborghini',
'kongregate',
'landlautomotive',
'kickasstorrent',
'khanacademy',
'kickstarter',
'intesasanpaolo',
'landrover',
'latimes',
'latamairlinesgroup',
'lastminute',
'legacy',
'lifehacker',
'linkedin',
'likes',
'lego',
'lifebuzz',
'lidl',
'mayoclinic',
'livestrong',
'marketwatch',
'liveleak',
'lloydstsb',
'mail',
'maserati',
'match',
'liverpoolfc',
'londonstockexchange',
'littlewoods',
'medium',
'mcafee',
'lockerdome',
'lizardgeo',
'LiveJournal',
'littlethings',
'mailchimp',
'mashable',
'lotterypost',
'llbean',
'LonelyPlanet',
'losmovies',
'lloydsbank',
'meetme',
'mcdonalds',
'lowes',
'mediafire',
'live',
'manutd',
'magportal',
'meetup',
'macys',
'MCBG',
'mandmdirect',
'megagames',
'marksandspencer',
'manchestereveningnews',
'lonewolvespvp',
'Minecraft',
'mg',
'microsoft',
'microsoftstore',
'metoffice',
'merriam8787878787webster',
'metro',
'metacafe',
'microsoftonline',
'mib',
'mercedes8787878787benz',
'minecraftskins',
'mapquest',
'migente',
'mizuho8787878787fg',
'mirror',
'mit',
'morrisons',
'mog',
'mmafighting',
'moneysavingexpert',
'motionempire',
'mini',
'miniclip',
'mooviemaniac',
'mint',
'marriott',
'MoshiMonsters',
'Moneysupermarket',
'mmajunkie',
'mixunit',
'monster',
'mitsubishi8787878787cars',
'movie4k',
'msn',
'mousebreaker',
'mtv',
'mufg',
'movie25',
'mumsnet',
'motors',
'mozilla',
'multiplication',
'mineplex',
'movie2k',
'mycashplus',
'mojang',
'livescore',
'missguided',
'maplin',
'myfitnesspal',
'myshopify',
'nationwide',
'nascar',
'nationalexpress',
'nametests',
'newsweek',
'naijapals',
'myhermes',
'netbet',
'nesn',
'mysynchrony',
'myspace',
'newegg',
'notdoppler',
'myway',
'nfl',
'mymaths',
'mysinglefriend',
'netmums',
'netflix',
'MyHappyGames',
'newslink',
'nick',
'nationalgeographic',
'neteller',
'mysupermarket',
'noaa',
'naver',
'nbcnews',
'myvue',
'newgrounds',
'mymail',
'nhs',
'nab',
'nike',
'nordstrom',
'mzhiphop',
'natwest',
'nhl',
'nba',
'next',
'newyorker',
'nitrome',
'nintendo',
'nextdoor',
'nexopia',
'national8787878787lottery',
'nbcsports',
'ning',
'norton',
'nationalrail',
'nordea',
'mywebsearch',
'nowtv',
'NinjaKiwi',
'nih',
'nwolb',
'npr',
'newlook',
'nytimes',
'ok',
'okcupid',
'ocado',
'nypost',
'nydailynews',
'officedepot',
'nyse',
'office365',
'odeon',
'OneMoreLevel',
'onthebeach',
'nbc',
'notonthehighstreet',
'pcadvisor',
'oracle',
'pcworld',
'patch',
'ownersdirect',
'Orbitz',
'pcmag',
'open',
'patheos',
'pearsoncmg',
'outlook',
'PaddyPower',
'outbrain',
'paypal',
'pandora',
'oovoo',
'pch',
'overstock',
'overclockers',
'papajohns',
'orkut',
'parade',
'opentable',
'parship',
'newsnow',
'people',
'photobucket',
'pgatour',
'perfspot',
'nasdaqomxnordic',
'piczo',
'pizzahut',
'pinterest',
'pixnet',
'pitchfork',
'pinkbike',
'PlayaBit',
'pinnaclesports',
'pistonheads',
'playdom',
'plus',
'pnc',
'pof',
'popsugar',
'politico',
'PocketGamer',
'Polygon',
'popcap',
'pogo',
'popads',
'porsche',
'powerball',
'postoffice',
'playstation',
'rollingstone',
'premierleague',
'pretty52',
'reed',
'rotoworld',
'realclearpolitics',
'rightmove',
'QuarterToThree',
'priceline',
'Reddit',
'preloved',
'premierinn',
'realtor',
'qualtrics',
'rbsdigital',
'rarbg',
'refinery29',
'reuters',
'rr',
'racingpost',
'radioshack',
'rolls8787878787royce',
'reference',
'rei',
'qvcuk',
'royalgames',
'quidco',
'rbs',
'ravelry',
'qvc',
'retailmenot',
'rd',
'riverisland',
'rspca',
'rottentomatoes',
'quora',
'redfin',
'redbox',
'runescape',
'runnersworld',
'saga',
'ryanair',
'salesforce',
'samsclub',
'sagepay',
'secondlife',
'sephora',
'schwab',
'shelfari',
'santander',
'screwfix',
'sears',
'samsung',
'scout',
'sbnation',
'sazuki',
'sc',
'shaadi',
'rhapsody',
'RPGamer',
'reimageplus',
'sharepoint',
'shareasale',
'sherdog',
'sberbank',
'searchlock',
'sfgate',
'Shockwave',
'shopify',
'showmyhomework',
'shutterstock',
'si',
'sina',
'silvergames',
'sickdeals',
'slideshare',
'slack',
'slimmingworld',
'slickdeals',
'skysports',
'skyrock',
'skype',
'sky',
'skybet',
'sogou',
'skiddle',
'smfg',
'solarmovie',
'slate',
'societegenerale',
'sohu',
'softtonic',
'royalmail',
'skyscanner',
'siteadvisor',
'soso',
'sportinglife',
'spotify',
'sportingbet',
'speedtest',
'sourceforge',
'spreadex',
'soundcloud',
'sportingnews',
'squarespace',
'southwest',
'sportsdirect',
'spareroom',
'sprint',
'sony',
'standard',
'stanford',
'stanjames',
'stackexchange',
'statestree',
'staples',
'quizlet',
'sse',
'steampowered',
'stubhub',
'stumbleupon',
'superdry',
'surveymonkey',
'subway',
'suntrust',
'stereogum',
'strava',
'stackoverflow',
'steamcommunity',
'swagbucks',
'swaseacity',
'swedbank',
'superdrug',
'suncorpbank',
'swarovski',
'tacobell',
'tagged',
't8787878787mobile',
'tea8787878787games',
'tesco',
'tbbank',
'taleo',
'taobao',
'ted',
'thedailybeast',
'tbs',
'techradar',
'tes',
'tattoodo',
'tescobank',
'target',
'talktalk',
'theatlantic',
'thefreedictionary',
'theblaze',
'telegraph',
'starbucks',
'thekitchn',
'theaa',
'theladbible',
'theguardian',
'thehindu',
'themeforest',
'thepennyhoarder',
'thepiratebay',
'theroot',
'thesaurus',
'thesportbible',
'sainsburys',
'thesun',
'thestudentroom',
'theverge',
'thetrainline',
'thetimes',
'thomson',
'theweek',
'thomascook',
'TIGSource',
'thismoney',
'ticketmaster',
'tiesto',
'thewatchseries',
'time',
'tkmaxx',
'three',
'timesofindia',
'titanbet',
'timeanddate',
'timewarnercables',
'tmall',
'timeout',
'tmz',
'today',
'tmx',
'topcashback',
'tomshardware',
'topix',
'totaljobs',
'todou',
'topman',
'toptal',
'torrentz',
'topshop',
'totesport',
'toysrus',
'roblox',
'Travelocity',
'tradedoubler',
'trello',
'travelrepublic',
'trivago',
'travbuddy',
'tripadvisor',
'trendsmap',
'taboola',
'travelsupermarket',
'trulia',
'TravelZoo',
'tse',
'tsn',
'ucas',
'uflix',
'united',
'tsb',
'Twitch',
'ufc',
'ubs',
'vanguard',
'twitter',
'usmagazine',
'ups',
'usbank',
'Twellow',
'usnews',
'usatoday',
'unibet',
'ustream',
'tweetdeck',
'tv',
'urbandictionary',
'uber',
'turntablelab',
'unilad',
'tumblr',
'uswitch',
'uol',
'usaa',
'tvguide',
'usps',
'trustpilot',
'vevo',
'viator',
'verizonwireless',
'vidics',
'Viewster',
'veoh',
'vice',
'victoriassecret',
'very',
'vid',
'unicreditgroup',
'vine',
'viralthread',
'virbo',
'Virginmedia',
'verizon',
'vistaprint',
'w3schools',
'vouchercode',
'vk',
'worldlifestyle',
'vue',
'woot',
'vodaphone',
'vivastreet',
'wilko',
'vox',
'walgreens',
'walmart',
'wizzair',
'wikihow',
'vodlocker',
'waitrose',
'williamhill',
'wnd',
'wix',
'wish',
'vumoo',
'wired',
'woodlands8787878787junior',
'wickes',
'wikia',
'whoscored',
'wikimedia',
'worldpay',
'wordreference',
'wikipedia',
'warcraft',
'wow',
'wowcher',
'xgenstudios',
'yellowpages',
'yahoo',
'wwe',
'worldstarhiphop',
'xbox',
'ybonline',
'xing',
'yandex',
'xfinity',
'yelp',
'wunderground',
'y8',
'yfrog',
'vimeo',
'wsj',
'yify8787878787torrent',
'zapak',
'youtube',
'youku',
'zappos',
'Ziddu',
'zendesk',
'zoopla',
'zergnet',
'zara',
'zillow',
'zoosk',
'Zynga',
'zulily',
'wordpress',
'shutterfly',
'trustedreviews',
'rakuten'];




var THREEx	= THREEx	|| {}

//////////////////////////////////////////////////////////////////////////////////
//		Constructor							//
//////////////////////////////////////////////////////////////////////////////////

/**
 * create a dynamic texture with a underlying canvas
 *
 * @param {Number} width  width of the canvas
 * @param {Number} height height of the canvas
 */
THREEx.DynamicTexture	= function(width, height){
  var canvas	= document.createElement( 'canvas' )
  canvas.width	= width
  canvas.height	= height
  this.canvas	= canvas

  var context	= canvas.getContext( '2d' )
  this.context	= context

  var texture	= new THREE.Texture(canvas)
  this.texture	= texture
}

//////////////////////////////////////////////////////////////////////////////////
//		methods								//
//////////////////////////////////////////////////////////////////////////////////

/**
 * clear the canvas
 *
 * @param  {String*} fillStyle 		the fillStyle to clear with, if not provided, fallback on .clearRect
 * @return {THREEx.DynamicTexture}      the object itself, for chained texture
 */
THREEx.DynamicTexture.prototype.clear = function(fillStyle){
  // depends on fillStyle
  if( fillStyle !== undefined ){
    this.context.fillStyle	= fillStyle
    this.context.fillRect(0,0,this.canvas.width, this.canvas.height)
  }else{
    this.context.clearRect(0,0,this.canvas.width, this.canvas.height)
  }
  // make the texture as .needsUpdate
  this.texture.needsUpdate	= true;
  // for chained API
  return this;
}

/**
 * draw text
 *
 * @param  {String}		text	- the text to display
 * @param  {Number|undefined}	x	- if provided, it is the x where to draw, if not, the text is centered
 * @param  {Number}		y	- the y where to draw the text
 * @param  {String*} 		fillStyle - the fillStyle to clear with, if not provided, fallback on .clearRect
 * @param  {String*} 		contextFont - the font to use
 * @return {THREEx.DynamicTexture}	- the object itself, for chained texture
 */
THREEx.DynamicTexture.prototype.drawText = function(text, x, y, fillStyle, contextFont){
  // set font if needed
  if( contextFont !== undefined )	this.context.font = contextFont;
  // if x isnt provided
  if( x === undefined || x === null ){
    var textSize	= this.context.measureText(text);
    x = (this.canvas.width - textSize.width) / 2;
  }
  // actually draw the text
  this.context.fillStyle = fillStyle;
  this.context.fillText(text, x, y);
  // make the texture as .needsUpdate
  this.texture.needsUpdate	= true;
  // for chained API
  return this;
};

THREEx.DynamicTexture.prototype.drawTextCooked = function(options){
  var context	= this.context
  var canvas	= this.canvas
  options		= options	|| {}
  var text	= options.text
  var params	= {
    margin		: options.margin !== undefined ? options.margin	: 0.1,
    lineHeight	: options.lineHeight !== undefined ? options.lineHeight : 0.1,
    align		: options.align !== undefined ? options.align : 'left',
    fillStyle	: options.fillStyle !== undefined ? options.fillStyle : 'black',
    font		: options.font !== undefined ? options.font : "bold "+(0.2*512)+"px Arial",
  }
  // sanity check
  console.assert(typeof(text) === 'string')

  context.save()
  context.fillStyle	= params.fillStyle;
  context.font		= params.font;

  var y	= (params.lineHeight + params.margin)*canvas.height
  while(text.length > 0 ){
    // compute the text for specifically this line
    var maxText	= computeMaxTextLength(text)
    // update the remaining text
    text	= text.substr(maxText.length)


    // compute x based on params.align
    var textSize	= context.measureText(maxText);
    if( params.align === 'left' ){
      var x	= params.margin*canvas.width
    }else if( params.align === 'right' ){
      var x	= (1-params.margin)*canvas.width - textSize.width
    }else if( params.align === 'center' ){
      var x = (canvas.width - textSize.width) / 2;
    }else	console.assert( false )

    // actually draw the text at the proper position
    this.context.fillText(maxText, x, y);

    // goto the next line
    y	+= params.lineHeight*canvas.height
  }
  context.restore()

  // make the texture as .needsUpdate
  this.texture.needsUpdate	= true;
  // for chained API
  return this;

  function computeMaxTextLength(text){
    var maxText	= ''
    var maxWidth	= (1-params.margin*2)*canvas.width
    while( maxText.length !== text.length ){
      var textSize	= context.measureText(maxText);
      if( textSize.width > maxWidth )	break;
      maxText	+= text.substr(maxText.length, 1)
    }
    return maxText
  }
}

/**
 * execute the drawImage on the internal context
 * the arguments are the same the official context2d.drawImage
 */
THREEx.DynamicTexture.prototype.drawImage	= function(/* same params as context2d.drawImage */){
  // call the drawImage
  this.context.drawImage.apply(this.context, arguments)
  // make the texture as .needsUpdate
  this.texture.needsUpdate	= true;
  // for chained API
  return this;
}
